version: '3.3'

services:
  postgres_oil:
    image: postgres:14
    env_file:
      - "./envs/postgres_oil.env"
    volumes:
      - "./init_oil:/docker-entrypoint-initdb.d"

  postgres_liq:
    image: postgres:14
    env_file:
      - "./envs/postgres_liq.env"
    volumes:
      - "./init_liq:/docker-entrypoint-initdb.d"

  postgres_zak:
    image: postgres:14
    env_file:
      - "./envs/postgres_zak.env"
    volumes:
      - "./init_zak:/docker-entrypoint-initdb.d"

  plot:
    build: ./geoprod_adapters

  oil:
    build: ./geoprod_oil/
    env_file:
      - "./envs/oil.env"
    depends_on:
      - postgres_oil

  liq:
    build: ./geoprod_liq/
    env_file:
      - "./envs/liq.env"
    depends_on:
      - postgres_liq

  zak:
    build: ./geoprod_zak/
    env_file:
      - "./envs/zak.env"
    depends_on:
      - postgres_zak

  com:
    build: ./geoprod_com/
    depends_on:
      - zak
      - liq

  inpoint:
    build: ./geoprod_inpoint/
    ports:
      - "80:8000"
    depends_on:
      - com
      - oil
      - plot
